global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
- job_name: fl_nodes
  static_configs:
  - targets:
    - node_0:8000
    - node_1:8000
    - node_2:8000
    - node_3:8000
    - node_4:8000
    - node_5:8000
    labels:
      group: training_nodes
